// <auto-generated />
using FitnessApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250405093918_AddWorkoutDayAndExerciseModels")]
    partial class AddWorkoutDayAndExerciseModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.API.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecondaryMuscles")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetMuscles")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "piept",
                            Description = "Exercițiu compus pentru piept, umeri și triceps.",
                            DifficultyLevel = "intermediar",
                            Equipment = "haltere, bancă",
                            Instructions = "1. Așezați-vă pe o bancă plată, cu picioarele pe podea. 2. Țineți halterele deasupra pieptului, cu palmele îndreptate înainte. 3. Coborâți halterele până când ating părțile laterale ale pieptului. 4. Împingeți halterele înapoi în poziția inițială.",
                            Name = "Împins la Piept cu Haltere",
                            SecondaryMuscles = "triceps",
                            TargetMuscles = "pectorali, deltoid anterior"
                        },
                        new
                        {
                            Id = 2,
                            Category = "piept",
                            Description = "Exercițiu de bază pentru partea superioară a corpului care utilizează greutatea corporală.",
                            DifficultyLevel = "începător",
                            Equipment = "niciunul",
                            Instructions = "1. Începeți în poziția de planșă, cu mâinile plasate puțin mai lat decât lățimea umerilor. 2. Coborâți corpul menținând o linie dreaptă de la cap la călcâie. 3. Opriți-vă când pieptul este la câțiva centimetri de sol. 4. Împingeți înapoi în poziția inițială.",
                            Name = "Flotări",
                            SecondaryMuscles = "triceps, abdomen, mușchii spatelui",
                            TargetMuscles = "pectorali, deltoid anterior"
                        },
                        new
                        {
                            Id = 3,
                            Category = "spate",
                            Description = "Exercițiu compus pentru lățimea spatelui și forța părții superioare a corpului.",
                            DifficultyLevel = "intermediar",
                            Equipment = "bară de tracțiuni",
                            Instructions = "1. Agățați-vă de bară cu palmele îndreptate în afară și mâinile plasate mai lat decât lățimea umerilor. 2. Trageți corpul în sus până când bărbia trece de bară. 3. Coborâți încet înapoi în poziția inițială.",
                            Name = "Tracțiuni la Bară",
                            SecondaryMuscles = "biceps, deltoid posterior, rotund",
                            TargetMuscles = "latissimus dorsi, rhomboid"
                        },
                        new
                        {
                            Id = 4,
                            Category = "spate",
                            Description = "Exercițiu pentru dezvoltarea părții mijlocii a spatelui și a forței de prindere.",
                            DifficultyLevel = "intermediar",
                            Equipment = "haltere",
                            Instructions = "1. Aplecați-vă în față cu picioarele la lățimea umerilor, ținând o halteră în fiecare mână. 2. Trageți halterele în sus către abdomen, menținând coatele aproape de corp. 3. Strângeți omoplații la sfârșit, apoi coborâți greutățile controlat.",
                            Name = "Vâslit cu Halteră",
                            SecondaryMuscles = "biceps, deltoid posterior",
                            TargetMuscles = "latissimus dorsi, rhomboid, trapez"
                        },
                        new
                        {
                            Id = 5,
                            Category = "picioare",
                            Description = "Exercițiu compus pentru dezvoltarea forței picioarelor și a părții inferioare a corpului.",
                            DifficultyLevel = "intermediar",
                            Equipment = "niciunul sau bară",
                            Instructions = "1. Stați cu picioarele la lățimea umerilor. 2. Coborâți șoldurile ca și cum v-ați așeza pe un scaun, menținând genunchii în linie cu degetele de la picioare. 3. Coborâți până când coapsele sunt paralele cu solul sau mai jos. 4. Împingeți prin călcâie pentru a reveni la poziția inițială.",
                            Name = "Genuflexiuni",
                            SecondaryMuscles = "ischiocruralii, adductori, mușchii spatelui",
                            TargetMuscles = "cvadriceps, gluteus maximus"
                        },
                        new
                        {
                            Id = 6,
                            Category = "picioare",
                            Description = "Exercițiu unilateral pentru picioare care vizează cvadricepsii, fesierii și ischiocruralii.",
                            DifficultyLevel = "intermediar",
                            Equipment = "niciunul sau gantere",
                            Instructions = "1. Stați în picioare cu picioarele la lățimea șoldurilor. 2. Faceți un pas mare înainte cu un picior. 3. Coborâți corpul până când ambii genunchi sunt îndoiți la aproximativ 90 de grade. 4. Împingeți prin piciorul din față pentru a reveni la poziția inițială.",
                            Name = "Lunges",
                            SecondaryMuscles = "ischiocruralii, mușchii gambei",
                            TargetMuscles = "cvadriceps, gluteus maximus"
                        },
                        new
                        {
                            Id = 7,
                            Category = "abdomen",
                            Description = "Exercițiu de bază pentru zona abdominală superioară.",
                            DifficultyLevel = "începător",
                            Equipment = "niciunul",
                            Instructions = "1. Întindeți-vă pe spate cu genunchii îndoiți și picioarele pe sol. 2. Puneți mâinile pe piept sau pe lângă cap. 3. Ridicați umerii și partea superioară a spatelui de pe sol, menținând zona lombară pe sol. 4. Coborâți încet înapoi la poziția de start.",
                            Name = "Crunch-uri",
                            SecondaryMuscles = "oblicii",
                            TargetMuscles = "rectus abdominis"
                        },
                        new
                        {
                            Id = 8,
                            Category = "abdomen",
                            Description = "Exercițiu izometric pentru întregul corp care vizează în principal miezul.",
                            DifficultyLevel = "începător",
                            Equipment = "niciunul",
                            Instructions = "1. Începeți în poziția de flotare, dar sprijinindu-vă pe antebrațe în loc de mâini. 2. Mențineți corpul într-o linie dreaptă de la cap la călcâie. 3. Încordați abdomenul și fesierii. 4. Țineți poziția pentru timpul dorit.",
                            Name = "Planșă",
                            SecondaryMuscles = "oblicii, mușchii spatelui, umerii",
                            TargetMuscles = "rectus abdominis, transversus abdominis"
                        },
                        new
                        {
                            Id = 9,
                            Category = "brațe",
                            Description = "Exercițiu clasic pentru dezvoltarea bicepsului.",
                            DifficultyLevel = "începător",
                            Equipment = "haltere",
                            Instructions = "1. Stați în picioare cu halterele în mâini, brațele întinse și palmele îndreptate înainte. 2. Îndoiți coatele și ridicați halterele spre umeri. 3. Strângeți bicepsul în partea de sus. 4. Coborâți halterele încet înapoi în poziția inițială.",
                            Name = "Flexii cu Haltera",
                            SecondaryMuscles = "brahialis, brahioradialis",
                            TargetMuscles = "biceps brachii"
                        },
                        new
                        {
                            Id = 10,
                            Category = "brațe",
                            Description = "Exercițiu pentru dezvoltarea mușchilor triceps.",
                            DifficultyLevel = "începător",
                            Equipment = "halteră",
                            Instructions = "1. Stați în picioare sau așezați cu o halteră ținută cu ambele mâini. 2. Ridicați haltera deasupra capului, cu brațele complet întinse. 3. Coborâți haltera în spatele capului îndoind coatele. 4. Extindeți brațele pentru a ridica haltera înapoi în poziția inițială.",
                            Name = "Extensii de Triceps",
                            SecondaryMuscles = "deltoid anterior, deltoid posterior",
                            TargetMuscles = "triceps brachii"
                        },
                        new
                        {
                            Id = 11,
                            Category = "umeri",
                            Description = "Exercițiu de izolare pentru deltoidul lateral.",
                            DifficultyLevel = "începător",
                            Equipment = "haltere",
                            Instructions = "1. Stați în picioare cu halterele în mâini de-a lungul corpului. 2. Ridicați halterele lateral până la nivelul umerilor, menținând brațele aproape drepte. 3. Coborâți încet înapoi în poziția inițială.",
                            Name = "Ridicări Laterale",
                            SecondaryMuscles = "trapez, deltoid anterior, deltoid posterior",
                            TargetMuscles = "deltoid lateral"
                        },
                        new
                        {
                            Id = 12,
                            Category = "umeri",
                            Description = "Exercițiu compus pentru dezvoltarea umerilor.",
                            DifficultyLevel = "intermediar",
                            Equipment = "haltere sau bară",
                            Instructions = "1. Stați în picioare sau așezați ținând halterele la nivelul umerilor. 2. Împingeți halterele în sus până când brațele sunt complet extinse. 3. Coborâți halterele înapoi la nivelul umerilor.",
                            Name = "Împins la Umeri",
                            SecondaryMuscles = "deltoid lateral, triceps, trapez superior",
                            TargetMuscles = "deltoid anterior"
                        },
                        new
                        {
                            Id = 13,
                            Category = "cardio",
                            Description = "Exercițiu cardiovascular de bază pentru îmbunătățirea sănătății inimii și arderea caloriilor.",
                            DifficultyLevel = "intermediar",
                            Equipment = "niciunul sau bandă de alergare",
                            Instructions = "1. Începeți cu un ritm ușor pentru încălzire. 2. Măriți treptat intensitatea până la ritmul dorit. 3. Mențineți o postură dreaptă, cu umerii relaxați. 4. Aterizați pe mijlocul piciorului, nu pe călcâi.",
                            Name = "Alergare",
                            SecondaryMuscles = "mușchii gambei, abdomen, mușchii spatelui",
                            TargetMuscles = "cvadriceps, ischiocruralii, gluteus maximus"
                        },
                        new
                        {
                            Id = 14,
                            Category = "cardio",
                            Description = "Exercițiu de intensitate ridicată pentru întregul corp.",
                            DifficultyLevel = "avansat",
                            Equipment = "niciunul",
                            Instructions = "1. Începeți în picioare. 2. Ajungeți într-o poziție de ghemuit. 3. Plasați mâinile pe sol și extindeți picioarele înapoi în poziția de flotare. 4. Faceți o flotare (opțional). 5. Aduceți picioarele înapoi în poziția de ghemuit. 6. Săriți în sus cu mâinile deasupra capului.",
                            Name = "Burpees",
                            SecondaryMuscles = "deltoid, triceps, abdomen, ischiocruralii",
                            TargetMuscles = "cvadriceps, gluteus maximus, pectorali"
                        },
                        new
                        {
                            Id = 15,
                            Category = "mobilitate",
                            Description = "Exercițiu de întindere pentru ischiocruralii și zona lombară.",
                            DifficultyLevel = "începător",
                            Equipment = "niciunul",
                            Instructions = "1. Așezați-vă pe sol cu picioarele întinse în față. 2. Încercați să atingeți degetele de la picioare, îndoind de la șold și menținând spatele cât mai drept posibil. 3. Țineți poziția timp de 20-30 de secunde. 4. Relaxați-vă și repetați.",
                            Name = "Stretching pentru Ischiocruralii",
                            SecondaryMuscles = "zona lombară",
                            TargetMuscles = "ischiocruralii"
                        });
                });

            modelBuilder.Entity("FitnessApp.API.Models.ExerciseWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("Technique")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("ExerciseWorkouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 5,
                            Notes = "Folosiți o bandă elastică plasată deasupra genunchilor pentru rezistență suplimentară",
                            Order = 1,
                            Reps = 15,
                            RestSeconds = 45,
                            Sets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 6,
                            Notes = "Alternați picioarele la fiecare repetiție",
                            Order = 2,
                            Reps = 12,
                            RestSeconds = 45,
                            Sets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 14,
                            Notes = "Versiune modificată pentru începători: fără flotare și fără săritură",
                            Order = 3,
                            Reps = 10,
                            RestSeconds = 60,
                            Sets = 3,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 4,
                            Duration = "2 minute",
                            ExerciseId = 13,
                            Notes = "Menține un ritm ridicat pentru cardio",
                            Order = 4,
                            Reps = 10,
                            RestSeconds = 60,
                            Sets = 2,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 5,
                            Duration = "30 secunde",
                            ExerciseId = 15,
                            Notes = "Mențineți poziția și respirați profund",
                            Order = 5,
                            Reps = 10,
                            RestSeconds = 15,
                            Sets = 2,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 2,
                            Notes = "Efectuați flotări cu genunchii pe sol dacă este necesar",
                            Order = 1,
                            Reps = 10,
                            RestSeconds = 45,
                            Sets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 11,
                            Notes = "Folosiți gantere ușoare și concentrate-vă pe tehnică",
                            Order = 2,
                            Reps = 12,
                            RestSeconds = 45,
                            Sets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 8,
                            Duration = "30 secunde",
                            ExerciseId = 8,
                            Notes = "Mențineți o linie dreaptă de la umeri la călcâie",
                            Order = 3,
                            Reps = 10,
                            RestSeconds = 45,
                            Sets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 7,
                            Notes = "Concentrați-vă pe contracția abdomenului la fiecare repetiție",
                            Order = 4,
                            Reps = 15,
                            RestSeconds = 45,
                            Sets = 3,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 1,
                            Notes = "Folosiți o greutate care vă permite să efectuați 10 repetări cu efort",
                            Order = 1,
                            Reps = 10,
                            RestSeconds = 90,
                            Sets = 4,
                            Weight = 20.0,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 2,
                            Notes = "Efectuați până la eșec pe ultimul set",
                            Order = 2,
                            Reps = 15,
                            RestSeconds = 60,
                            Sets = 3,
                            WorkoutDayId = 5
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 10,
                            Notes = "Concentrați-vă pe contracția tricepsului la vârful mișcării",
                            Order = 3,
                            Reps = 12,
                            RestSeconds = 60,
                            Sets = 3,
                            Weight = 15.0,
                            WorkoutDayId = 5
                        });
                });

            modelBuilder.Entity("FitnessApp.API.Models.FitnessProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeRangeMax")
                        .HasColumnType("int");

                    b.Property<int?>("AgeRangeMin")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequiredEquipment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WorkoutsPerWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FitnessPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRangeMax = 60,
                            AgeRangeMin = 18,
                            Description = "Program de 8 săptămâni pentru femei, conceput pentru pierderea în greutate prin combinarea exercițiilor cardio cu antrenamente de rezistență. Acest program se concentrează pe crearea unui deficit caloric și tonifierea întregului corp.",
                            Diet = "vegetarian",
                            DifficultyLevel = "începător",
                            DurationWeeks = 8,
                            Gender = "femeie",
                            Goals = "Pierdere în greutate, îmbunătățirea condiției fizice, tonifierea musculară",
                            ImageUrl = "/images/programs/female-weight-loss.jpg",
                            Name = "Program de Slăbit pentru Femei",
                            ProgramType = "slabit",
                            RequiredEquipment = "Benzi elastice, gantere ușoare, saltea de fitness",
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            Id = 2,
                            AgeRangeMax = 45,
                            AgeRangeMin = 18,
                            Description = "Program de 12 săptămâni pentru bărbați, conceput pentru creșterea masei musculare. Utilizează principiile hipertrofiei progresive, combinând exerciții compuse grele cu izolări specifice pentru maximizarea creșterii musculare.",
                            Diet = "carnivor",
                            DifficultyLevel = "intermediar",
                            DurationWeeks = 12,
                            Gender = "barbat",
                            Goals = "Creșterea masei musculare, îmbunătățirea forței, dezvoltarea proporțională a corpului",
                            ImageUrl = "/images/programs/male-muscle-building.jpg",
                            Name = "Program de Masă Musculară pentru Bărbați",
                            ProgramType = "masa",
                            RequiredEquipment = "Haltere, bare, bancă de fitness, aparat cablu",
                            WorkoutsPerWeek = 5
                        },
                        new
                        {
                            Id = 3,
                            AgeRangeMax = 65,
                            AgeRangeMin = 18,
                            Description = "Program de 6 săptămâni pentru îmbunătățirea condiției fizice generale, potrivit pentru toate nivelurile de fitness. Combină antrenamentele de forță cu exerciții cardio pentru o abordare echilibrată a fitness-ului.",
                            Diet = "vegetarian",
                            DifficultyLevel = "începător",
                            DurationWeeks = 6,
                            Gender = "unisex",
                            Goals = "Îmbunătățirea condiției fizice generale, tonifiere ușoară, creșterea energiei și vitalității",
                            ImageUrl = "/images/programs/general-fitness.jpg",
                            Name = "Program de Fitness General Unisex",
                            ProgramType = "fit",
                            RequiredEquipment = "Gantere ușoare, bandă elastică, saltea de fitness",
                            WorkoutsPerWeek = 3
                        });
                });

            modelBuilder.Entity("FitnessApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessApp.API.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AllergiesRestrictions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<double>("WeightGoal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("FitnessApp.API.Models.WorkoutDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek");

                    b.HasIndex("ProgramId");

                    b.ToTable("WorkoutDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            DurationMinutes = 45,
                            Name = "Ziua 1 - Cardio și Partea Inferioară",
                            Notes = "Focus pe intensitate moderată și volum ridicat pentru arderea caloriilor",
                            ProgramId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 3,
                            DurationMinutes = 40,
                            Name = "Ziua 2 - Partea Superioară și Core",
                            Notes = "Concentrare pe tonifierea brațelor, spatelui și zonei abdominale",
                            ProgramId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 5,
                            DurationMinutes = 30,
                            Name = "Ziua 3 - Full Body HIIT",
                            Notes = "Antrenament de înaltă intensitate pentru maximizarea arderilor de calorii",
                            ProgramId = 1
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 6,
                            DurationMinutes = 35,
                            Name = "Ziua 4 - Mobilitate și Stretching Activ",
                            Notes = "Focus pe recuperare, flexibilitate și mobilitate",
                            ProgramId = 1
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 1,
                            DurationMinutes = 60,
                            Name = "Ziua 1 - Piept și Triceps",
                            Notes = "Focus pe exerciții compuse pentru piept cu volume mai mari pentru triceps",
                            ProgramId = 2
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 2,
                            DurationMinutes = 60,
                            Name = "Ziua 2 - Spate și Biceps",
                            Notes = "Accent pe lățimea și grosimea spatelui, urmat de izolări pentru biceps",
                            ProgramId = 2
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 4,
                            DurationMinutes = 70,
                            Name = "Ziua 3 - Picioare",
                            Notes = "Antrenament complet pentru picioare cu accent pe cvadricepși, ischiocruralii și fesieri",
                            ProgramId = 2
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 5,
                            DurationMinutes = 60,
                            Name = "Ziua 4 - Umeri și Abdomen",
                            Notes = "Dezvoltarea tuturor celor trei capete ale deltoidului și consolidarea zonei centrale",
                            ProgramId = 2
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 6,
                            DurationMinutes = 50,
                            Name = "Ziua 5 - Full Body (Accent pe Puncte Slabe)",
                            Notes = "Antrenament personalizabil care se concentrează pe grupele musculare care necesită atenție suplimentară",
                            ProgramId = 2
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 1,
                            DurationMinutes = 45,
                            Name = "Ziua 1 - Full Body Strength",
                            Notes = "Antrenament de forță pentru întregul corp cu accent pe tehnica corectă",
                            ProgramId = 3
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 3,
                            DurationMinutes = 40,
                            Name = "Ziua 2 - Cardio & Core",
                            Notes = "Combinație de exerciții cardio cu intervale și antrenament pentru zona mediană",
                            ProgramId = 3
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 5,
                            DurationMinutes = 50,
                            Name = "Ziua 3 - Mobilitate & Forță",
                            Notes = "Focus pe mobilitate și exerciții funcționale de forță",
                            ProgramId = 3
                        });
                });

            modelBuilder.Entity("FitnessApp.API.Models.ExerciseWorkout", b =>
                {
                    b.HasOne("FitnessApp.API.Models.Exercise", "Exercise")
                        .WithMany("ExerciseWorkouts")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessApp.API.Models.WorkoutDay", "WorkoutDay")
                        .WithMany("ExerciseWorkouts")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("FitnessApp.API.Models.UserProfile", b =>
                {
                    b.HasOne("FitnessApp.API.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FitnessApp.API.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.API.Models.WorkoutDay", b =>
                {
                    b.HasOne("FitnessApp.API.Models.FitnessProgram", "Program")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("FitnessApp.API.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseWorkouts");
                });

            modelBuilder.Entity("FitnessApp.API.Models.FitnessProgram", b =>
                {
                    b.Navigation("WorkoutDays");
                });

            modelBuilder.Entity("FitnessApp.API.Models.User", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FitnessApp.API.Models.WorkoutDay", b =>
                {
                    b.Navigation("ExerciseWorkouts");
                });
#pragma warning restore 612, 618
        }
    }
}
